# Generated by Django 4.2 on 2024-08-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_customuser1_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_writer",
        ),
    ]
