# Generated by Django 4.2 on 2024-09-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_user_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='user',
        ),
    ]
