# Generated by Django 4.2 on 2024-09-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_email_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
